# Generated by Django 2.0.3 on 2019-04-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('day', models.CharField(blank=True, max_length=255, null=True)),
                ('weather', models.CharField(blank=True, max_length=255, null=True)),
                ('temperature_high', models.CharField(blank=True, max_length=255, null=True)),
                ('temperature_lower', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
